name: Combine PRs

on:
  push:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.0.0
        with:
          branch_prefix: renovate
          labels: dependencies,combined-pr
