name: Changesets
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  packages:
    uses: driimus/shared-workflows/.github/workflows/publish.yml@main
    secrets: inherit
